### ISSUE TITLE
Coming soon page 3

### ISSUE THREAD

**Issue by davidbanu** [ThemeStack/HtmlPages#10]
# Tasks 
- [ ] Add design ideas in the comment section 
- [ ] The page will be static - as simple as it can be
- [ ] Fully responsive
- [ ] Pixel perfect design 
- [ ] Upload the code into this repository

NOTE: CSS resources should go into the style folder - we should use link for the Bootstrap library
