### ISSUE TITLE
Signup page 2

### ISSUE THREAD

**Issue by davidbanu** [ThemeStack/HtmlPages#17]
# Tasks 
- [ ] Add design ideas in the comment section 
- [ ] The page will be static 
- [ ] Fully responsive
- [ ] Pixel perfect design 
- [ ] Upload the code into this repository
- [ ] Password field should be hidden 

NOTE: CSS resources should go into the style folder - we should use link for the Bootstrap library
