### ISSUE TITLE
Shop Cart

### ISSUE THREAD

**Issue by davidbanu** [ThemeStack/HtmlPages#25]
## Tasks 

- [ ] dynamic functionality - remove item + update quantity
- [ ] Fully responsiveness
- [ ] Pixel perfect design 
- [ ] Update everything to this repository 

Note: We should add documentation for js scripts
