### ISSUE TITLE
Image Carousel 

### ISSUE THREAD

**Issue by davidbanu** [ThemeStack/HtmlPages#26]
## Tasks 

- [ ] dynamic functionality - find cool effect 
- [ ] Fully responsiveness
- [ ] Pixel perfect design 
- [ ] Update everything into this repository 

Note: We should add documentation for js scripts
