### ISSUE TITLE
Pricing and timeframe slider 

### ISSUE THREAD

**Issue by davidbanu** [ThemeStack/HtmlPages#27]
## Tasks 

- [ ] Add designs and ideas in comments
- [ ] Dynamic functionality 
- [ ] Fully responsiveness
- [ ] Pixel perfect design 
- [ ] Update everything into this repository 

Note: We should add documentation for js scripts
