### ISSUE TITLE
Contact Us page 3

### ISSUE THREAD

**Issue by davidbanu** [ThemeStack/HtmlPages#5]
# Tasks 
- [ ] Add design ideas in the comment section 
- [ ] Fully responsive
- [ ] Pixel perfect design 
- [ ] Upload the code into this repository

NOTE: CSS resources should go into the style folder - we should use link for the Bootstrap library
